name: dml4fluxes
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cudatoolkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip
  - pip:
    - doubleml
    - econml
    - dowhy
    - shap
    - lightgbm
    - statsmodels
    - jax
    - jaxlib
    - optax
    - tqdm